// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Note struct {
	ID        int64          `json:"id"`
	Nombre    string         `json:"nombre"`
	Contenido sql.NullString `json:"contenido"`
}

type NoteTag struct {
	NoteID int64 `json:"note_id"`
	TagID  int64 `json:"tag_id"`
}

type Tag struct {
	ID     int64          `json:"id"`
	Nombre string         `json:"nombre"`
	Color  sql.NullString `json:"color"`
}

type User struct {
	ID           int64  `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}
