// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	// sql/queries/query.sql
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	DeleteNote(ctx context.Context, id int64) error
	GetNote(ctx context.Context, id int64) (Note, error)
	GetTag(ctx context.Context, id int64) (Tag, error)
	GetTagsForNote(ctx context.Context, noteID int64) ([]Tag, error)
	LinkTagToNote(ctx context.Context, arg LinkTagToNoteParams) error
	ListNotes(ctx context.Context) ([]Note, error)
	ListTags(ctx context.Context) ([]Tag, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) error
}

var _ Querier = (*Queries)(nil)
